@startuml

class RelatedProductBrandsController {
 + getProductBrandsByCategory(string|int $category, BrandsProductsAction $action): JsonApiResourceCollection|JsonResponse
}

class BrandsProductsAction {
    + handle(): Collection
}

RelatedProductBrandsController -> BrandsProductsAction
@enduml