@startuml
left to right direction

actor "Менеджер" as Manager

rectangle "Система інтернет-магазину" {
  usecase "Додавання нового менеджера" as UC1
  usecase "Створення купонів" as UC2
  usecase "Перегляд замовлень клієнтів" as UC3
  usecase "Створення/оновлення товарів" as UC4
  usecase "Перегляд товарів\nпо категоріях" as UC5
  usecase "Створення/редагування/\nвидалення категорії" as UC6
  usecase "Додавання/редагування брендів" as UC7
  usecase "Публікація/видалення товару" as UC8
  usecase "Перегляд товарів\nна складі" as UC9
  usecase "Оновлення кількості товарів" as UC10
  usecase "Управління знижками" as UC11
  usecase "Налаштування слайдеру та секцій" as UC12
}

Manager --> UC1
Manager --> UC2
Manager --> UC3
Manager --> UC4
Manager --> UC5
Manager --> UC6
Manager --> UC7
Manager --> UC8
Manager --> UC9
Manager --> UC10
Manager --> UC11
Manager --> UC12
@enduml
