@startuml
class CategoriesBrandController {
    + getCategoriesForBrand(string|int $brandId,BrandCategoriesAction $action): JsonApiResourceCollection|JsonResponse
}

class BrandCategoriesAction {
    + handle(): Collection
}

CategoriesBrandController ..> BrandCategoriesAction
@enduml