@startuml

class CategoryOptionAttributesController {
    + __construct(CacheService $cacheService)

    + getOptionAttributesForCategory(string $categorySlug, GetAttributesAction $action): JsonApiResourceCollection|JsonResponse
}

class CacheService {
    + __construct(Repository $repository)

    + key(): string

    + repo(): Repository
}

class GetAttributesAction {
    + handle(): BaseCollection

    - mapAttributes(): BaseCollection
}

interface Repository {
    + remember($key, $ttl, $closure)
}

CategoryOptionAttributesController --> CacheService
CategoryOptionAttributesController ..> GetAttributesAction : uses
CacheService --> Repository

@enduml