CREATE DATABASE IF NOT EXISTS expelliarmus ENCODING = 'UTF8';

ALTER DATABASE expelliarmus OWNER TO postgres;

CREATE DATABASE IF NOT EXISTS expelliarmus_test ENCODING = 'UTF8';

ALTER DATABASE expelliarmus OWNER TO postgres;